// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIv91TANK_p5S6UXVtkaftpWmx3NDRh8',
    appId: '1:1013700630712:web:8b6144e829b991f411fc4d',
    messagingSenderId: '1013700630712',
    projectId: 'meal-app-flutter-e2d1a',
    authDomain: 'meal-app-flutter-e2d1a.firebaseapp.com',
    storageBucket: 'meal-app-flutter-e2d1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JL-i7hQPaZPCgsaTuqRtXBpKkaBVNmg',
    appId: '1:1013700630712:android:0995251b8f0edabe11fc4d',
    messagingSenderId: '1013700630712',
    projectId: 'meal-app-flutter-e2d1a',
    storageBucket: 'meal-app-flutter-e2d1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9D3kzzJWt5nKyT1mLsKQ_Knh88OUClYU',
    appId: '1:1013700630712:ios:f0d6b0e96d67554c11fc4d',
    messagingSenderId: '1013700630712',
    projectId: 'meal-app-flutter-e2d1a',
    storageBucket: 'meal-app-flutter-e2d1a.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9D3kzzJWt5nKyT1mLsKQ_Knh88OUClYU',
    appId: '1:1013700630712:ios:f0d6b0e96d67554c11fc4d',
    messagingSenderId: '1013700630712',
    projectId: 'meal-app-flutter-e2d1a',
    storageBucket: 'meal-app-flutter-e2d1a.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjIv91TANK_p5S6UXVtkaftpWmx3NDRh8',
    appId: '1:1013700630712:web:90018508ae7d071e11fc4d',
    messagingSenderId: '1013700630712',
    projectId: 'meal-app-flutter-e2d1a',
    authDomain: 'meal-app-flutter-e2d1a.firebaseapp.com',
    storageBucket: 'meal-app-flutter-e2d1a.firebasestorage.app',
  );

}